language: node_js
node_js:
  - 'stable'

cache: yarn

script:
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  strategy: git
  app:
    master: giv-loftschool-nodejs-hw-05
